import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';
import { jsPDF } from 'npm:jspdf@4.2.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const payload = await req.json();
    const { period_label, period_start, period_end, org_id } = payload;

    // Fetch organization and infrastructure assets
    const org = org_id ? await base44.entities.Organization.get(org_id) : null;
    const assets = org_id
      ? await base44.entities.InfraAsset.filter({ organization_id: org_id }, "-created_date", 100)
      : [];

    // Create PDF document
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    // Colors
    const colors = {
      primary: [45, 81, 158],      // Navy
      accent: [245, 158, 11],       // Gold
      text: [33, 33, 33],           // Dark gray
      lightText: [118, 118, 118],   // Medium gray
      white: [255, 255, 255],
      healthy: [34, 197, 94],       // Green
      warning: [251, 146, 60],      // Orange
      critical: [239, 68, 68],      // Red
      offline: [107, 114, 128],     // Gray
    };

    // Header
    doc.setFillColor(...colors.primary);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(...colors.white);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('EDS Sentrix ASM', 15, 20);

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Monthly Compliance Report', 15, 28);

    // Report metadata
    doc.setTextColor(...colors.lightText);
    doc.setFontSize(9);
    doc.text(`Report Period: ${period_label}`, 15, 35);

    // Organization info
    let yPos = 50;
    doc.setTextColor(...colors.text);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Organization Overview', 15, yPos);

    yPos += 8;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(...colors.text);
    doc.text(`Organization: ${org?.name || 'N/A'}`, 15, yPos);

    yPos += 6;
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 15, yPos);

    yPos += 6;
    doc.text(`Generated By: ${user.full_name || user.email}`, 15, yPos);

    // Asset Summary Stats
    yPos += 10;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Infrastructure Asset Summary', 15, yPos);

    yPos += 8;
    const healthyCount = assets.filter(a => a.status === 'healthy').length;
    const warningCount = assets.filter(a => a.status === 'warning').length;
    const criticalCount = assets.filter(a => a.status === 'critical').length;
    const offlineCount = assets.filter(a => a.status === 'offline').length;
    const totalAssets = assets.length;
    const healthPercent = totalAssets > 0 ? Math.round((healthyCount / totalAssets) * 100) : 0;

    // Summary boxes
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(...colors.lightText);
    doc.text(`Total Assets: ${totalAssets}`, 15, yPos);
    yPos += 5;
    doc.text(`Healthy: ${healthyCount} (${healthPercent}%)`, 15, yPos);
    yPos += 5;
    doc.text(`Warning: ${warningCount}`, 15, yPos);
    yPos += 5;
    doc.text(`Critical: ${criticalCount}`, 15, yPos);
    yPos += 5;
    doc.text(`Offline: ${offlineCount}`, 15, yPos);

    // Asset Details Table
    yPos += 10;
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(...colors.text);
    doc.text('Asset Status Details', 15, yPos);

    yPos += 8;
    // Table header
    doc.setFillColor(...colors.primary);
    doc.setTextColor(...colors.white);
    doc.setFontSize(9);
    doc.setFont(undefined, 'bold');
    doc.rect(15, yPos - 4, 180, 6, 'F');
    doc.text('Asset Name', 18, yPos);
    doc.text('Type', 90, yPos);
    doc.text('Status', 130, yPos);
    doc.text('Provider', 160, yPos);

    yPos += 8;
    doc.setTextColor(...colors.text);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(8);

    // Table rows
    assets.forEach((asset, idx) => {
      // Page break if needed
      if (yPos > 260) {
        doc.addPage();
        yPos = 15;
      }

      // Alternate row background
      if (idx % 2 === 0) {
        doc.setFillColor(240, 240, 240);
        doc.rect(15, yPos - 3, 180, 5, 'F');
      }

      // Status color coding
      let statusColor = colors.healthy;
      if (asset.status === 'warning') statusColor = colors.warning;
      else if (asset.status === 'critical') statusColor = colors.critical;
      else if (asset.status === 'offline') statusColor = colors.offline;

      doc.setTextColor(...statusColor);
      doc.text(asset.asset_name || '—', 18, yPos);

      doc.setTextColor(...colors.text);
      doc.text(asset.asset_type || '—', 90, yPos);
      doc.text(asset.status || '—', 130, yPos);
      doc.text(asset.provider || '—', 160, yPos);

      yPos += 5;
    });

    // Compliance Notes
    yPos += 8;
    doc.setTextColor(...colors.text);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('Compliance Status', 15, yPos);

    yPos += 6;
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    const complianceStatus =
      criticalCount > 0
        ? '⚠ CRITICAL ISSUES DETECTED — Immediate action required'
        : warningCount > 0
        ? '⚠ WARNING — Review and address flagged assets'
        : '✓ COMPLIANT — All assets within acceptable parameters';

    doc.text(complianceStatus, 15, yPos);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...colors.lightText);
    doc.text('This is an automatically generated compliance report. For support, contact EDS Sentrix ASM Support.', 15, 285);

    // Generate PDF as base64
    const pdfBase64 = doc.output('datauristring').split(',')[1];

    return Response.json({
      success: true,
      pdf_base64: pdfBase64,
      filename: `EDS-Compliance-Report-${period_label.replace(/\s+/g, '-')}.pdf`,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});